# .travis.yml
dist: focal
language: php

php:
  - 7.4
  - 8.0

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp .env.travis .env
  - php artisan chemex:install --no-interaction
